### ISSUE TITLE
cime crashed for nemsio input on Hera

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-mrweather-app#181]
cime crashed for nemsio input on hera for the test of intel c768 

hfe06:/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/ufs-mrweather-app-workflow.c768>./case.build
Building case in directory /scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/ufs-mrweather-app-workflow.c768
sharedlib_only is False
model_only is False
Generating component namelists as part of build
Creating component namelists
  2020-09-01 03:52:37 atm 
   Calling /scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/src/model/FV3/cime/cime_config/buildnml
Checking /scratch2/BMC/det/lpan/hera/test/mrw//ufs_inputdata/icfiles/202008/20200831 directory to find raw input files ...
Found 'atm.input.ic.nemsio' in input directory
CHGRES namelist option 'input_type' is set to gaussian
CHGRES will use /scratch2/BMC/det/lpan/hera/test/mrw//ufs_inputdata/icfiles/202008/20200831/atm.input.ic.nemsio
removing file /scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/ufs-mrweather-app-workflow.c768/Buildconf/ufsatm.input_data_list
	Linking input namelist for ufsatm
Using /scratch1/BMC/gmtb/software/NCEPLIBS-ufs-v1.1.0/intel-18.0.5.274/impi-2018.0.4/share/postxconfig-NT-GFS.txt for post-processing
Using /scratch1/BMC/gmtb/software/NCEPLIBS-ufs-v1.1.0/intel-18.0.5.274/impi-2018.0.4/share/postxconfig-NT-GFS-F00.txt for post-processing
	Creating INPUT and RESTART directory
Traceback (most recent call last):
  File "./case.build", line 165, in <module>
    _main_func(__doc__)
  File "./case.build", line 160, in _main_func
    use_old=use_old, ninja=ninja, dry_run=dry_run)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 727, in case_build
    return run_and_log_case_status(functor, cb, caseroot=caseroot)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1768, in run_and_log_case_status
    rv = func()
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 721, in <lambda>
    save_build_provenance, use_old, ninja, dry_run)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 661, in _case_build_impl
    model_only, buildlist)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 326, in _build_checks
    case.create_namelists()
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 91, in create_namelists
    (self, caseroot, compname), case=self)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 413, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/src/model/FV3/cime/cime_config/buildnml", line 1291, in buildnml
    _create_namelist_chgres(case, confdir, config, namelist_infile, nmlgen_chgres, nmlgen_chgres_def, nmlgen_input, namelist_user, input_type)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/src/model/FV3/cime/cime_config/buildnml", line 860, in _create_namelist_chgres
    nmlgen.set_value('atm_files_input_grid', 'atm.input.ic.nemsio') 
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/nmlgen.py", line 247, in set_value
    literals = self._to_namelist_literals(name, value)
  File "/scratch2/BMC/det/lpan/hera/test/mrw/08312020/intel_nemsio/ufs-mrweather-app/cime/scripts/Tools/../../scripts/lib/CIME/nmlgen.py", line 205, in _to_namelist_literals
    values[i] = self.quote_string(scalar)
TypeError: 'str' object does not support item assignment

**Comment by pjpegion** [comment]
@panll That error looks like a python3 vs python2 issue.  What version of python are you using?

**Comment by panll** [comment]
i am using python2 @pjpegion

**Comment by panll** [comment]
python2.7.5

**Comment by pjpegion** [comment]
hmm,  the times I saw a similar error was when I was using python3 when I need to use python2.

**Comment by ligiabernardet** [comment]
@uturuncoglu Any ideas?

**Comment by uturuncoglu** [comment]
@ligiabernardet I need to try on Cheyenne to see it is reproducible or not. If not, it could be hard for me to track down the issue and fix it without access to Hera. Let me try and I'll update you.

**Comment by climbfuji** [comment]
> @ligiabernardet I need to try on Cheyenne to see it is reproducible or not. If not, it could be hard for me to track down the issue and fix it without access to Hera. Let me try and I'll update you.

hera is down today anyway

**Comment by uturuncoglu** [comment]
@climbfuji okay, thanks. it gives me time to test it.

**Comment by uturuncoglu** [comment]
@ligiabernardet @panll @pjpegion I could reproduce the problem and fix it. It was related with the minor problem in UFSATM CIME interface and not related with the Python version. It will be available in the next update of the app. First, i need to have a PR in CIME side.

**Comment by panll** [comment]
Thanks! @uturuncoglu
